name: beer_app
description: Beer App to demonstrate the Pagination with BLoC in Flutter
publish_to: 'none'
version: 1.0.0+1
authors:
  - Tirth Patel
homepage: https://github.com/piedcipher/beer-app
repository: https://github.com/piedcipher/beer-app
issue_tracker: https://github.com/piedcipher/beer-app/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_bloc: ^6.1.1
  http: ^0.12.2
  json_annotation: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.11
  json_serializable: ^3.5.1

flutter:
  uses-material-design: true